//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaziMarket1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_BaziMarket_Entities1 : DbContext
    {
        public Db_BaziMarket_Entities1()
            : base("name=Db_BaziMarket_Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_Cart> T_Cart { get; set; }
        public virtual DbSet<T_Comment> T_Comment { get; set; }
        public virtual DbSet<T_Description> T_Description { get; set; }
        public virtual DbSet<T_Group> T_Group { get; set; }
        public virtual DbSet<T_Picture> T_Picture { get; set; }
        public virtual DbSet<T_Product> T_Product { get; set; }
        public virtual DbSet<T_ProductCart> T_ProductCart { get; set; }
        public virtual DbSet<T_Property> T_Property { get; set; }
        public virtual DbSet<T_Question> T_Question { get; set; }
        public virtual DbSet<T_Role> T_Role { get; set; }
        public virtual DbSet<T_Specification> T_Specification { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
        public virtual DbSet<T_Discount> T_Discount { get; set; }
    }
}
