//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaziMarket1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Comment
    {
        public int CommentId { get; set; }
        public int CommentRate { get; set; }
        public Nullable<int> CommentUserId { get; set; }
        public Nullable<int> CommentProductId { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CommentRegisterId { get; set; }
    
        public virtual T_Product T_Product { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
