//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaziMarket1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Description
    {
        public int DescriptionId { get; set; }
        public string DecriptionTitle { get; set; }
        public string DecriptionContent { get; set; }
        public string DescriptionImageName { get; set; }
        public Nullable<int> DescriptionProductId { get; set; }
    
        public virtual T_Product T_Product { get; set; }
    }
}
