//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaziMarket1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Discount
    {
        public int DiscountId { get; set; }
        public string DiscountCode { get; set; }
        public Nullable<int> DiscountMaximum { get; set; }
        public Nullable<int> DiscountGroupId { get; set; }
        public Nullable<int> DiscountProductId { get; set; }
        public double DiscountPercent { get; set; }
    
        public virtual T_Group T_Group { get; set; }
        public virtual T_Product T_Product { get; set; }
    }
}
